### ISSUE TITLE
I like your project

### ISSUE THREAD

**Issue by lucabae** [ehtisham91/Django-Speech-to-text-Chat#2]
Hello, I'm writing from UpWork, you applied for my startup and I wanted to let you know I'm interested in you to take part of the team, please leave a contact email so that we can talk more further if you are interested

**Comment by ehtisham91** [comment]
Here you go: ehtishamashraf90@gmail.com

Please delete this issue, as this comment has nothing to do with this project.

**Comment by ehtisham91** [comment]
@L1Lbg  Here you go: ehtishamashraf90@gmail.com

Please delete this issue, as this comment has nothing to do with this project.
